import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/context/AuthContext";

const roboto = Geist({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto} antialiased mx-auto  p-4 `}>
        <ThemeProvider attribute="class">
          <AuthProvider>
            <div className="container mx-auto">{children}</div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
